GET http://127.0.0.1:5000/todo/api/tasks

GET http://127.0.0.1:5000/todo/api/tasks/1

GET http://127.0.0.1:5000/todo/api/tasks/3

POST http://127.0.0.1:5000/todo/api/tasks
Content-Type: application/json
{
    "title": "Read OpenAPI book"
}